name: RPG Automation
on: [push]
jobs:
  compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make re

  fetch_repo:
    needs: compilation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@github.com:EpitechPromo2026/B-MUL-200-BDX-2-1-myrpg-edouard.pradie.git
        ssh_private_key:
          ${{ secrets.SSH_PRIVATE_KEY }}